In [1]:
import numpy as np

In [4]:
imgarray=np.ones([20,4])

In [6]:
print(imgarray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
for i in range(20):
    for j in range(4):
        imgarray[i,j]=2*j+i

In [11]:
print(imgarray)

[[ 0.  2.  4.  6.]
 [ 1.  3.  5.  7.]
 [ 2.  4.  6.  8.]
 [ 3.  5.  7.  9.]
 [ 4.  6.  8. 10.]
 [ 5.  7.  9. 11.]
 [ 6.  8. 10. 12.]
 [ 7.  9. 11. 13.]
 [ 8. 10. 12. 14.]
 [ 9. 11. 13. 15.]
 [10. 12. 14. 16.]
 [11. 13. 15. 17.]
 [12. 14. 16. 18.]
 [13. 15. 17. 19.]
 [14. 16. 18. 20.]
 [15. 17. 19. 21.]
 [16. 18. 20. 22.]
 [17. 19. 21. 23.]
 [18. 20. 22. 24.]
 [19. 21. 23. 25.]]
