In [1]:
import numpy as np
List=np.array([1,2,3,4])
List=List*2
print(List)

[2 4 6 8]


In [3]:
list1=np.zeros([2,3])
print(list1)
list1[0][2]=8.9
print(list1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0.  0.  8.9]
 [0.  0.  0. ]]


In [48]:
list2=np.empty([2,2,3,4,2],dtype="int")

print(list2)



In [49]:
list2.ndim

5

In [50]:
list1.dtype

dtype('float64')

In [51]:
list2


array([[[[[ 979269792,        403],
          [ 979507120,        403],
          [      1096,          0],
          [         4,          0]],

         [[       600,          0],
          [       411,          0],
          [       928,          0],
          [       411,        403]],

         [[       464,          0],
          [       411,        403],
          [       908,          0],
          [       411,        403]]],


        [[[       472,          0],
          [       411,        403],
          [      1000,          0],
          [       411,        403]],

         [[      1088,          0],
          [       411,        403],
          [      1096,          0],
          [       411,        403]],

         [[      1040,          0],
          [       411,        403],
          [      1068,          0],
          [       411,        403]]]],



       [[[[      1096,          0],
          [         4,        403],
          [1065446984,        403],
          

In [42]:
list2[1,2,3,1]=97

In [43]:
list2

array([[[[4128860, 6029375],
         [3801155, 5242972],
         [7274610, 7471207],
         [7143521, 6357060]],

        [[6357108, 4259932],
         [6357102, 7274595],
         [6553710, 3342433],
         [7077980, 6422633]],

        [[7536732, 7602281],
         [2949221, 6357104],
         [7012451, 6750305],
         [7536741, 7209052]]],


       [[[7143541, 7929968],
         [7471196, 7209057],
         [7274596, 6029421],
         [7602285, 6357106]],

        [[6553710, 6488110],
         [3342448, 2949175],
         [6881399, 6226030],
         [7143521, 3539044]],

        [[3014708, 7929968],
         [3014756, 3014706],
         [7274563, 6684782],
         [6750313,      97]]]])

In [2]:
list3=np.empty([3,4],dtype)

NameError: name 'dtype' is not defined

In [3]:
list3=np.eye(4)

In [4]:
list3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
list3=list3*list3

In [6]:
list3


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
list3=[[2,3],[6,7]]

In [19]:
list3=np.array(list3)

### 

In [15]:
list3


array([[2, 3],
       [6, 7]])

In [11]:
list3=list3*list3

In [20]:
list3

array([[2, 3],
       [6, 7]])

In [16]:
list3=np.asmatrix(list3)*list3

In [17]:
list3

matrix([[22, 27],
        [54, 67]])